rvm: true
before_script:
  - cp .env.peakflow .env.local
  - wait-for-it mariadb:3306
  - cd spec/dummy && bundle exec rails db:environment:set db:create db:schema:load RAILS_ENV=test
services:
  mariadb:
    environment:
      MARIADB_USER: peakflow
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: active_record_auto_validations_test
    image: mariadb:latest
    expose:
      - 3306
    mem_limit: 4096m
    restart_policy: always
builds:
  build_1:
    environment:
      RUBY_VERSION: 2.7.6
    name: Ruby 2.7.6
    script:
      - bundle exec rspec
  build_2:
    environment:
      RUBY_VERSION: 3.0.4
    name: Ruby 3.0.4
    script:
      - bundle exec rspec
  build_3:
    environment:
      RUBY_VERSION: 3.1.2
    name: Ruby 3.1.2
    script:
      - bundle exec rspec
  build_4:
    name: Linters
    script:
      - bundle exec rubocop
