rvm: true
before_script:
  - cp .env.peakflow .env.local
  - wait-for-it mariadb:3306
  - cd spec/dummy && bundle exec rails db:environment:set db:create db:schema:load RAILS_ENV=test
services:
  mariadb:
    environment:
      MARIADB_USER: peakflow
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: active_record_auto_validations_test
    image: mariadb:latest
    expose:
      - 3306
    mem_limit: 4096m
    restart_policy: always
builds:
  build_1:
    environment:
      BUNDLE_GEMFILE: /home/build/project/gemfiles/ruby_3.gemfile
      RUBY_VERSION: 3.2.7
    name: Ruby 3.2.7
    script:
      - bundle exec appraisal "ruby 3" rspec
  build_2:
    environment:
      BUNDLE_GEMFILE: /home/build/project/gemfiles/ruby_3.gemfile
      RUBY_VERSION: 3.3.7
    name: Ruby 3.3.7
    script:
      - bundle exec appraisal "ruby 3" rspec
  build_3:
    environment:
      BUNDLE_GEMFILE: /home/build/project/gemfiles/ruby_3.gemfile
      RUBY_VERSION: 3.4.2
    name: Ruby 3.4.2
    script:
      - bundle exec appraisal "ruby 3" rspec
  build_4:
    name: Linters
    script:
      - bundle exec rubocop
